with source as (

    select *
    from read_csv(
        '/Users/leandrosantos/Downloads/cnpj-lakehouse-pipeline/data/raw/estabelecimentos_sample.csv',
        delim=';',
        quote='"',
        escape='"',
        header=false,
        encoding='latin-1',
        columns={
            'cnpj_basico': 'varchar',
            'cnpj_ordem': 'varchar',
            'cnpj_dv': 'varchar',
            'identificador_matriz_filial': 'varchar',
            'nome_fantasia': 'varchar',
            'situacao_cadastral': 'varchar',
            'data_situacao_cadastral': 'varchar',
            'motivo_situacao_cadastral': 'varchar',
            'nome_cidade_exterior': 'varchar',
            'pais': 'varchar',
            'data_inicio_atividade': 'varchar',
            'cnae_fiscal_principal': 'varchar',
            'cnae_fiscal_secundaria': 'varchar',
            'tipo_logradouro': 'varchar',
            'logradouro': 'varchar',
            'numero': 'varchar',
            'complemento': 'varchar',
            'bairro': 'varchar',
            'cep': 'varchar',
            'uf': 'varchar',
            'municipio': 'varchar',
            'ddd_1': 'varchar',
            'telefone_1': 'varchar',
            'ddd_2': 'varchar',
            'telefone_2': 'varchar',
            'ddd_fax': 'varchar',
            'fax': 'varchar',
            'correio_eletronico': 'varchar',
            'situacao_especial': 'varchar',
            'data_situacao_especial': 'varchar'
        }
    )

)

select
    trim(cnpj_basico) as cnpj_basico,
    trim(cnpj_ordem) as cnpj_ordem,
    trim(cnpj_dv) as cnpj_dv,
    trim(cnpj_basico) || trim(cnpj_ordem) || trim(cnpj_dv) as cnpj_completo,
    trim(identificador_matriz_filial) as identificador_matriz_filial,
    {{ normalize_text('nome_fantasia') }} as nome_fantasia,
    trim(situacao_cadastral) as situacao_cadastral,
    {{ parse_yyyymmdd('data_situacao_cadastral') }} as data_situacao_cadastral,
    {{ normalize_text('motivo_situacao_cadastral') }} as motivo_situacao_cadastral,
    {{ normalize_text('nome_cidade_exterior') }} as nome_cidade_exterior,
    {{ normalize_text('pais') }} as pais,
    {{ parse_yyyymmdd('data_inicio_atividade') }} as data_inicio_atividade,
    trim(cnae_fiscal_principal) as cnae_fiscal_principal,
    {{ normalize_text('cnae_fiscal_secundaria') }} as cnae_fiscal_secundaria,
    {{ normalize_text('tipo_logradouro') }} as tipo_logradouro,
    {{ normalize_text('logradouro') }} as logradouro,
    {{ normalize_text('numero') }} as numero,
    {{ normalize_text('complemento') }} as complemento,
    {{ normalize_text('bairro') }} as bairro,
    {{ normalize_text('cep') }} as cep,
    trim(uf) as uf,
    trim(municipio) as municipio,
    {{ normalize_text('ddd_1') }} as ddd_1,
    {{ normalize_text('telefone_1') }} as telefone_1,
    {{ normalize_text('ddd_2') }} as ddd_2,
    {{ normalize_text('telefone_2') }} as telefone_2,
    {{ normalize_text('ddd_fax') }} as ddd_fax,
    {{ normalize_text('fax') }} as fax,
    {{ normalize_text('correio_eletronico') }} as correio_eletronico,
    {{ normalize_text('situacao_especial') }} as situacao_especial,
    {{ parse_yyyymmdd('data_situacao_especial') }} as data_situacao_especial
from source
